### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by 1736103466** [fangwei716/30-days-of-react-native#11]
使用Xcode编译时，GLLmage.m 83行 Property 'request' not found on object of type 'RCTImageSource *'
初学者不懂

**Comment by fangwei716** [comment]
先安装好 node.js (v5.x), npm install -g react-native-cli ,  & cocoapods
npm install
然后xcode 编译

**Comment by fangwei716** [comment]
Somehow the RNGL fetched from npm is breaking the app. 
Use https://github.com/fangwei716/30-days-of-react-native/tree/with_node_modules for now.
You don't need to run npm install. You can build directly.
