### ISSUE TITLE
Property 'request' not found on object of type 'RCTImageSource *'

### ISSUE THREAD

**Issue by haiqingMa** [fangwei716/30-days-of-react-native#12]
30-days-of-react-native/node_modules/gl-react-native/ios/GLImage.m:83:68: 
Property 'request' not found on object of type 'RCTImageSource *'

Line #83: _loading = [_bridge.imageLoader loadImageWithURLRequest:source.request
ErrorInfo: Property 'request' not found on object of type 'RCTImageSource *'

**Comment by fangwei716** [comment]
Require node.js (v5.x), npm install -g react-native-cli , xcode & cocoapods
and then, make sure you run npm install before you compile in xcode.

**Comment by haiqingMa** [comment]
My node.js version is v4.2.4, Can I run it?

--------------------------------------------------------------
30-days-of-react-native xxx$ sudo npm install
Password:
npm WARN peerDependencies The peer dependency react@^0.14.5 || ^15.0.0 included from gl-react will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
 
> utf-8-validate@1.2.1 install /Users/mhq/Documents/program/30-days-of-react-native/node_modules/react-native/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
 
> bufferutil@1.2.1 install /Users/mhq/Documents/program/30-days-of-react-native/node_modules/react-native/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
 
> fsevents@1.0.12 install /Users/mhq/Documents/program/30-days-of-react-native/node_modules/react-native/node_modules/fbjs-scripts/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/mhq/Documents/program/30-days-of-react-native/node_modules/react-native/node_modules/fbjs-scripts/node_modules/babel/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
 
> spawn-sync@1.0.15 postinstall /Users/mhq/Documents/program/30-days-of-react-native/node_modules/react-native/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

 
> spawn-sync@1.0.15 postinstall /Users/mhq/Documents/program/30-days-of-react-native/node_modules/react-native/node_modules/yeoman-environment/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> node postinstall

clamp@1.0.1 node_modules/clamp

react-native-swiper@1.4.5 node_modules/react-native-swiper

react-native-swipe-cards@0.0.7 node_modules/react-native-swipe-cards

fuzzy@0.1.1 node_modules/fuzzy

react-native-scrollable-tab-view@0.4.4 node_modules/react-native-scrollable-tab-view

react-native-gesture-password@0.1.5 node_modules/react-native-gesture-password

react-timer-mixin@0.13.3 node_modules/react-timer-mixin

react-native-quick-actions@0.1.4 node_modules/react-native-quick-actions

react-native-touch-id@1.2.4 node_modules/react-native-touch-id

react-native-blur@0.7.11 node_modules/react-native-blur

react-native-search-bar@2.11.0 node_modules/react-native-search-bar

react-native-linear-gradient@1.5.12 node_modules/react-native-linear-gradient

react-native-chart@0.1.14 node_modules/react-native-chart

react-native-video@0.7.1 node_modules/react-native-video
└── keymirror@0.1.1

gl-react-native@2.28.0 node_modules/gl-react-native
├── promise-defer@1.0.0
└── invariant@2.2.0 (loose-envify@1.2.0)

react-native-loading-spinner-overlay@0.0.8 node_modules/react-native-loading-spinner-overlay
├── react-native-gifted-spinner@0.0.3
└── autobind-decorator@1.3.3

react@15.1.0 node_modules/react
├── object-assign@4.1.0
├── loose-envify@1.2.0 (js-tokens@1.0.3)
└── fbjs@0.8.3 (immutable@3.8.1, ua-parser-js@0.7.10, core-js@1.2.6, promise@7.1.1, isomorphic-fetch@2.2.1)

gl-react@2.2.4 node_modules/gl-react
├── promise-defer@1.0.0
└── invariant@2.2.0 (loose-envify@1.2.0)

react-native-vector-icons@1.3.4 node_modules/react-native-vector-icons
├── lodash@4.13.1
└── yargs@3.32.0 (decamelize@1.2.0, y18n@3.2.1, camelcase@2.1.1, window-size@0.1.4, os-locale@1.4.0, cliui@3.2.0, string-width@1.0.1)

react-native@0.21.0 node_modules/react-native
├── absolute-path@0.0.0
├── graceful-fs@4.1.4
├── underscore@1.8.3
├── progress@1.1.8
├── stacktrace-parser@0.1.3
├── base64-js@0.0.8
├── semver@5.2.0
├── wordwrap@1.0.0
├── event-target-shim@1.1.1
├── immutable@3.8.1
├── image-size@0.3.5
├── rebound@0.0.13
├── art@0.10.1
├── debug@2.2.0 (ms@0.7.1)
├── opn@3.0.3 (object-assign@4.1.0)
├── json5@0.4.0
├── source-map@0.4.4 (amdefine@1.0.0)
├── bser@1.0.2 (node-int64@0.4.0)
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── node-fetch@1.5.3 (is-stream@1.1.0, encoding@0.1.12)
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
├── promise@7.1.1 (asap@2.0.4)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── react@0.14.8 (envify@3.4.1)
├── joi@6.10.1 (topo@1.1.0, isemail@1.2.0, hoek@2.16.3, moment@2.13.0)
├── babel-polyfill@6.3.14 (babel-regenerator-runtime@6.5.0, babel-runtime@5.8.38, core-js@1.2.6)
├── babel-register@6.4.3 (path-exists@1.0.0, home-or-tmp@1.0.0, source-map-support@0.2.10, babel-runtime@5.8.38, lodash@3.10.1, core-js@1.2.6)
├── fbjs@0.6.1 (whatwg-fetch@0.9.0, ua-parser-js@0.7.10, loose-envify@1.2.0, core-js@1.2.6)
├── react-transform-hmr@1.0.4 (global@4.3.0, react-proxy@1.1.8)
├── babylon@6.4.5 (babel-runtime@5.8.38)
├── babel-plugin-external-helpers@6.4.0 (babel-runtime@5.8.38)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── worker-farm@1.3.1 (xtend@4.0.1, errno@0.1.4)
├── ws@0.8.1 (options@0.0.6, ultron@1.0.2, utf-8-validate@1.2.1, bufferutil@1.2.1)
├── sane@1.4.0 (fb-watchman@1.9.0, watch@0.10.0, minimist@1.2.0, exec-sh@0.2.0, walker@1.0.7, minimatch@3.0.2)
├── yargs@3.32.0 (y18n@3.2.1, decamelize@1.2.0, camelcase@2.1.1, window-size@0.1.4, os-locale@1.4.0, cliui@3.2.0, string-width@1.0.1)
├── jstransform@11.0.3 (object-assign@2.1.1, base62@1.1.1, esprima-fb@15001.1.0-dev-harmony-fb, commoner@0.10.4)
├── babel-types@6.4.5 (to-fast-properties@1.0.2, esutils@2.0.2, lodash@3.10.1, babel-runtime@5.8.38, babel-traverse@6.10.4)
├── babel-core@6.4.5 (slash@1.0.0, shebang-regex@1.0.0, path-exists@1.0.0, path-is-absolute@1.0.0, private@0.1.6, convert-source-map@1.2.0, source-map@0.5.6, lodash@3.10.1, minimatch@2.0.10, babel-runtime@5.8.38, babel-helpers@6.8.0, babel-template@6.9.0, babel-code-frame@6.11.0, babel-messages@6.8.0, babel-generator@6.11.0, babel-traverse@6.10.4)
├── uglify-js@2.6.4 (async@0.2.10, uglify-to-browserify@1.0.2, source-map@0.5.6, yargs@3.10.0)
├── module-deps@3.9.1 (browser-resolve@1.11.2, through2@1.1.1, inherits@2.0.1, duplexer2@0.0.2, defined@1.0.0, xtend@4.0.1, subarg@1.0.0, resolve@1.1.7, detective@4.3.1, concat-stream@1.4.10, JSONStream@1.1.3, readable-stream@1.1.14, stream-combiner2@1.0.2, parents@1.0.1)
├── yeoman-environment@1.6.1 (escape-string-regexp@1.0.5, log-symbols@1.0.2, text-table@0.2.0, diff@2.2.3, untildify@2.1.0, grouped-queue@0.3.2, lodash@4.13.1, globby@4.1.0, mem-fs@1.1.3, inquirer@1.1.0)
├── babel-preset-react-native@1.9.0 (babel-plugin-react-transform@2.0.2, babel-plugin-syntax-flow@6.8.0, babel-plugin-check-es2015-constants@6.8.0, babel-plugin-transform-es2015-spread@6.8.0, babel-plugin-transform-es2015-arrow-functions@6.8.0, babel-plugin-syntax-async-functions@6.8.0, babel-plugin-transform-class-properties@6.10.2, babel-plugin-transform-react-jsx-source@6.9.0, babel-plugin-transform-es2015-template-literals@6.8.0, babel-plugin-syntax-jsx@6.8.0, babel-plugin-transform-es2015-literals@6.8.0, babel-plugin-transform-es2015-destructuring@6.9.0, babel-plugin-transform-object-assign@6.8.0, babel-plugin-syntax-class-properties@6.8.0, babel-plugin-syntax-trailing-function-commas@6.8.0, babel-plugin-transform-es2015-for-of@6.8.0, babel-plugin-transform-flow-strip-types@6.8.0, babel-plugin-transform-react-display-name@6.8.0, babel-plugin-transform-object-rest-spread@6.8.0, babel-plugin-transform-es2015-block-scoping@6.10.1, babel-plugin-transform-es2015-parameters@6.9.0, babel-plugin-transform-es2015-shorthand-properties@6.8.0, babel-plugin-transform-es2015-modules-commonjs@6.10.3, babel-plugin-transform-react-jsx@6.8.0, babel-plugin-transform-es2015-classes@6.9.0, babel-plugin-transform-regenerator@6.9.0, babel-plugin-transform-es2015-function-name@6.9.0, babel-plugin-transform-es2015-computed-properties@6.8.0)
├── connect@2.30.2 (cookie@0.1.3, cookie-signature@1.0.6, on-headers@1.0.1, pause@0.1.0, content-type@1.0.2, fresh@0.3.0, vhost@3.0.2, response-time@2.3.1, parseurl@1.3.1, basic-auth-connect@1.0.0, bytes@2.1.0, cookie-parser@1.3.5, utils-merge@1.0.0, depd@1.0.1, qs@4.0.0, method-override@2.3.6, express-session@1.11.3, finalhandler@0.4.0, type-is@1.6.13, errorhandler@1.4.3, compression@1.5.2, http-errors@1.3.1, connect-timeout@1.6.2, serve-favicon@2.3.0, morgan@1.6.1, body-parser@1.13.3, multiparty@3.3.2, csurf@1.8.3, serve-static@1.10.3, serve-index@1.7.3)
├── regenerator@0.8.46 (regenerator-runtime@0.9.5, private@0.1.6, through@2.3.8, esprima-fb@15001.1001.0-dev-harmony-fb, recast@0.10.33, commoner@0.10.4, defs@1.1.1)
├── fbjs-scripts@0.4.0 (object-assign@4.1.0, core-js@1.2.6, through2@2.0.1, gulp-util@3.0.7, babel@5.8.38)
└── yeoman-generator@0.20.3 (read-chunk@1.0.1, detect-conflict@1.0.0, path-exists@1.0.0, path-is-absolute@1.0.0, yeoman-welcome@1.0.1, async@1.5.2, mime@1.3.4, text-table@0.2.0, dargs@4.1.0, diff@2.2.3, class-extend@0.1.2, shelljs@0.5.3, lodash@3.10.1, nopt@3.0.6, istextorbinary@1.0.2, underscore.string@3.3.4, user-home@2.0.0, xdg-basedir@2.0.0, sinon@1.17.4, glob@5.0.15, run-async@0.1.0, findup-sync@0.2.1, rimraf@2.5.2, through2@2.0.1, yeoman-assert@2.2.1, html-wiring@1.2.0, cli-table@0.3.1, inquirer@0.8.5, cross-spawn@2.2.3, gruntfile-editor@1.2.0, github-username@2.1.0, dateformat@1.0.12, pretty-bytes@2.0.1, download@4.4.3, mem-fs-editor@2.2.1)

xxxx:30-days-of-react-native xxx$ npm --version
2.14.12
xxxx:30-days-of-react-native xxx$ node -v
v4.2.4

**Comment by fangwei716** [comment]
It requires at least node 5.0.0

**Comment by falltodis** [comment]
My node version is V5.8.0 and I got this error too.

**Comment by fangwei716** [comment]
Somehow the RNGL fetched from npm is breaking the app. 
Use https://github.com/fangwei716/30-days-of-react-native/tree/with_node_modules for now.
You don't need to run npm install. You can build directly.
