### ISSUE TITLE
Day18 在Android上运行拖拽时出错。

### ISSUE THREAD

**Issue by guanjian520** [fangwei716/30-days-of-react-native#14]
![image](https://cloud.githubusercontent.com/assets/5764481/16557010/e099a16e-420f-11e6-899d-25349ba4189f.png)

 this.animations = {
      duration: 200,
      create: {
        **type: LayoutAnimation.Types.linear,**
      },
      update: {
        **type: LayoutAnimation.Types.linear,**
        springDamping: 0.7,
      },
    };
 day18.js在android上运行时能正确显示里面的图标，但是在拖动图标的时候出错，将linear改为别的也会出错。

**Comment by fangwei716** [comment]
Please refer to this issue: https://github.com/facebook/react-native/issues/5267

**Comment by guanjian520** [comment]
我是已经设置UIManager.setLayoutAnimationEnabledExperimental(true);之后还出错的。

**Comment by fangwei716** [comment]
Sorry, I have no experience on this issue since I am not ready to support Android version.

**Comment by guanjian520** [comment]
嗯，谢谢！期望早点支持Android啊！

**Comment by toearth** [comment]
```javascript
this.animations = {
    duration: 200,
    create: {
        type: LayoutAnimation.Types.linear,
        property: LayoutAnimation.Properties.opacity,
    },
   update: {
        type: LayoutAnimation.Types.linear,
        springDamping: 0.7,
   },
};
```
Config like this
