### ISSUE TITLE
Property request not found on object of type 'RCTImageSource *'

### ISSUE THREAD

**Issue by xujianfei** [fangwei716/30-days-of-react-native#15]
Property request not found on object of type 'RCTImageSource *'

**Comment by falltodis** [comment]
me too.

**Comment by falltodis** [comment]
If you just want to test ,del RNGL from lib and unimport Day1

**Comment by xujianfei** [comment]
RNGL ？ where

**Comment by fangwei716** [comment]
Somehow the RNGL fetched from npm is breaking the app. 
Use https://github.com/fangwei716/30-days-of-react-native/tree/with_node_modules  for now.
You don't need to run npm install. You can build directly.

**Comment by fangwei716** [comment]
Also you can git clone again. I have disable RNGL for now.

**Comment by amitneeman** [comment]
Hi, ive tried to clone again and still get this error. should I just use the version with node_modules?

**Comment by fangwei716** [comment]
Yes. Go to the node_modules branch. Thanks.
