### ISSUE TITLE
运行回报这些错误

### ISSUE THREAD

**Issue by RabbitBell** [fangwei716/30-days-of-react-native#18]
![3b0e6318-1bfa-41b7-adde-2c209d0627e2](https://cloud.githubusercontent.com/assets/10183022/18612746/d1761ab2-7d94-11e6-8304-3cbe8a482597.png)

**Comment by fangwei716** [comment]
RN V0.22 is not compatible with XCode 8.

**Comment by RabbitBell** [comment]
thanksヽ(•̀ω•́ )ゝ啊哒
            在2016年09月18日 11:43，Wei Fang 写道:RN V0.22 is not compatible with XCode 8. 

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/fangwei716/30-days-of-react-native","title":"fangwei716/30-days-of-react-native","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/fangwei716/30-days-of-react-native"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fangwei716 in #18: RN V0.22 is not compatible with XCode 8. "}],"action":{"name":"View Issue","url":"https://github.com/fangwei716/30-days-of-react-native/issues/18#issuecomment-247823299"}}}

**Comment by fangwei716** [comment]
I am updating the project to support Xcode 8. You can check out the branch: development. Thanks.
