### ISSUE TITLE
xcode降级到7.3.1运行还是会报错

### ISSUE THREAD

**Issue by RabbitBell** [fangwei716/30-days-of-react-native#19]
<img width="375" alt="87f934a2-04fd-4d1d-a86b-e834faaf4bb8" src="https://cloud.githubusercontent.com/assets/10183022/18660038/ed9122b6-7f40-11e6-8bb3-bc37c6ceafa2.png">

**Comment by fangwei716** [comment]
I am updating the project to support Xcode 8. You can check out the branch: development. Thanks.
