### ISSUE TITLE
react-native ios-run has some error. help me please

### ISSUE THREAD

**Issue by daiweixiong** [fangwei716/30-days-of-react-native#20]
Hi,  react-native ios-run has problem. help me please. i copy the  error infomation as the below:
/Users/daiweixiong/Documents/workplace/RN/30-days-of-react-native/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:482:3: error: 
      ignoring return value of function declared with warn_unused_result
      attribute [-Werror,-Wunused-result]
  SecRandomCopyBytes(kSecRandomDefault, keyBytes.length, keyBytes.mutableBytes);
  ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/daiweixiong/Documents/workplace/RN/30-days-of-react-native/node_modules/react-native/Libraries/WebSocket/RCTSRWebSocket.m:1324:5: error: 
      ignoring return value of function declared with warn_unused_result
      attribute [-Werror,-Wunused-result]
    SecRandomCopyBytes(kSecRandomDefault, sizeof(uint32_t), (uint8_t *)mask_key);
    ^~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.

The following build commands failed:
	CompileC /Users/daiweixiong/Documents/workplace/RN/30-days-of-react-native/ios/build/Build/Intermediates/RCTWebSocket.build/Debug-iphonesimulator/RCTWebSocket.build/Objects-normal/x86_64/RCTSRWebSocket.o RCTSRWebSocket.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Installing build/Build/Products/Debug-iphonesimulator/ThirtyDaysOfReactNative.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist
/Users/daiweixiong/Documents/workplace/RN/30-days-of-react-native/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ThirtyDaysOfReactNative.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by daiweixiong** [comment]
Adding More Information：my node version is v6.3.0，Xcode version :8.0

**Comment by daiweixiong** [comment]
react-native-cli: 1.0.0
react-native: 0.21.0

**Comment by fangwei716** [comment]
RN0.21 is not compatible with XCode 8.0.

**Comment by daiweixiong** [comment]
thank you  , and then, which RN version should i install to match XCode 8.0

**Comment by fangwei716** [comment]
The latest RN is compatible with XCode 8.0, but not compatible with current version of this project.

**Comment by fangwei716** [comment]
I am updating the project to support Xcode 8. You can check out the branch: development. Thanks.
