### ISSUE TITLE
react native v0.26支持

### ISSUE THREAD

**Issue by jiafuzhang** [fangwei716/30-days-of-react-native#5]
你好，很喜欢你的这个项目，但是运行不起来。
希望能早日提供react native v0.26的支持，加油。
我会持续关注你的更新，祝好！

**Comment by fangwei716** [comment]
Thanks. Check out the branch for RN-V0.25, it should be compatible with RN-V0.26. https://github.com/fangwei716/30-days-of-react-native/tree/RN%400.25
